steps:
  #Maven image for packaging 
  - name: maven:3.3-jdk-8
    entrypoint: mvn
    args: ['package']
  # Apply Docker build and tag 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-build-images/mvn-app', '.']
  # Push docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-build-images/mvn-app']
 #Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run','deploy', 'my-spark-app', '--image' ,'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-build-images/mvn-app:latest','--region','us-central1', '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
